### ISSUE TITLE
Discrepancy between official action inputs and documentation

### ISSUE THREAD

**Issue by qubitz** [webbertakken/unity-test-runner#57]
I noticed that `unityVersion` is the only input according to [action.yml](https://github.com/webbertakken/unity-test-runner/blob/master/action.yml), but obviously this is not the case according to the [documentation](https://github.com/marketplace/actions/unity-test-runner). The reason I bring this up is I was looking for the official default values for option `projectPath` that I assumed was specified in action.yml.

Which brings me to my underlying question: what is the default value of  `projectPath`? 

In the documentation it says it is equal to `<your project root>`, but how would the action know what the project root is without the `projectPath` option?

**Comment by webbertakken** [comment]
Hi @qubitz and thank you for your feedback.

And I must say that you are spot on. In reality the source of truth for input is Input.js and with project root what I really meant to say is workspace root. 

For both points changes will have to be made. Not just in this repository, but in all unity actions.

**Comment by qubitz** [comment]
Ah, thanks for pointing me at input.js, Github actions with javascript is not my thing (yet).

Seems that the default value for `projectPath` is `.` currently ([line 19](https://github.com/webbertakken/unity-test-runner/blob/master/src/model/input.js#L19)). Would this be the the current working directory the host is in before calling the action or is this the equivalent to `github.workspace`?

**Comment by webbertakken** [comment]
As far as I understand, those two things are identical.
